
# ═══════════════════════════════════════════════════════════════
# 🚀 Generated by GitMaxer (Free Plan)
# 🔗 Upgrade at https://gitmaxer.vercel.app for watermark-free code
# ═══════════════════════════════════════════════════════════════

# --- Learning Objective ---
# This tutorial will teach you how to generate beautiful fractal art in Python
# by implementing recursive drawing algorithms. We'll focus on the concept of recursion
# and how it can be used to create self-similar patterns.
# We will use the `turtle` module for easy graphical drawing.

import turtle
import math # We'll use math for some calculations if needed, but turtle handles most.

# --- Global Settings for the Turtle Canvas ---
# These constants control the appearance and behavior of our drawing.
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
DRAWING_SPEED = 0 # 0 means fastest, higher numbers are slower.
PEN_COLOR = "blue"
BACKGROUND_COLOR = "white"

# --- Fractal Drawing Function (Recursive) ---
# This is the core of our fractal generation.
# A recursive function is one that calls itself.
# This is perfect for fractals because they are patterns that repeat at different scales.

def draw_fractal(turtle_obj, length, level, angle):
    """
    Draws a fractal pattern using recursion.

    Args:
        turtle_obj (turtle.Turtle): The turtle object used for drawing.
        length (float): The current length of the line segment to draw.
        level (int): The current recursion depth. Controls how many times the pattern repeats.
        angle (float): The angle at which branches split.
    """
    # --- Base Case ---
    # This is the condition that stops the recursion.
    # Without a base case, the function would call itself forever.
    # When the level reaches 0, we stop drawing this branch.
    if level == 0:
        return # Exit the function, stopping this branch of recursion.

    # --- Recursive Step ---
    # This is where the function calls itself to create the fractal pattern.

    # 1. Draw the current segment.
    # We move the turtle forward by 'length' pixels.
    turtle_obj.forward(length)

    # 2. Save the turtle's current state (position and heading).
    # This is crucial for returning to the correct position after drawing sub-fractals.
    current_position = turtle_obj.position()
    current_heading = turtle_obj.heading()

    # 3. Draw the left sub-fractal.
    # We turn left by 'angle' degrees.
    turtle_obj.left(angle)
    # We call 'draw_fractal' again, but with a shorter length (typically length * scale_factor)
    # and a reduced level (level - 1) to go deeper into the fractal.
    # The scale factor is often between 0 and 1. Here we'll use 0.7.
    draw_fractal(turtle_obj, length * 0.7, level - 1, angle)

    # 4. Restore the turtle's state to draw the right sub-fractal.
    # We need to go back to where we were before drawing the left sub-fractal.
    turtle_obj.setposition(current_position)
    turtle_obj.setheading(current_heading)

    # 5. Draw the right sub-fractal.
    # We turn right by 'angle' degrees.
    turtle_obj.right(angle)
    # Call 'draw_fractal' again for the right branch.
    draw_fractal(turtle_obj, length * 0.7, level - 1, angle)

    # 6. Restore the turtle's state again to allow the parent call to continue.
    # This ensures that the turtle is in the correct position and orientation
    # for the next part of the drawing at the higher level.
    turtle_obj.setposition(current_position)
    turtle_obj.setheading(current_heading)

    # --- Optional: Draw the segment again if you want a thicker look for non-base cases ---
    # This can make the main trunk and branches more prominent.
    # turtle_obj.forward(length)

# --- Setup and Execution ---
def main():
    """
    Sets up the turtle screen and initiates the fractal drawing.
    """
    # Create a screen object. This is our drawing window.
    screen = turtle.Screen()
    screen.setup(SCREEN_WIDTH, SCREEN_HEIGHT)
    screen.bgcolor(BACKGROUND_COLOR)
    screen.title("Recursive Fractal Art Generator")

    # Create a turtle object. This is our "pen".
    artist = turtle.Turtle()
    artist.speed(DRAWING_SPEED) # Set the drawing speed.
    artist.color(PEN_COLOR)    # Set the pen color.
    artist.hideturtle()        # Hide the turtle icon while drawing for a cleaner look.
    artist.penup()             # Lift the pen so it doesn't draw while moving to the start.

    # --- Starting Position and Orientation ---
    # Move the turtle to the bottom center of the screen to start drawing.
    artist.goto(0, -SCREEN_HEIGHT / 2 + 50)
    # Point the turtle upwards (90 degrees).
    artist.setheading(90)
    artist.pendown()           # Put the pen down to start drawing.

    # --- Fractal Parameters ---
    initial_length = 150  # The length of the first segment (the trunk).
    recursion_level = 7   # The depth of recursion. Higher levels mean more detail but take longer.
    branch_angle = 25     # The angle at which branches split.

    # --- Start the Drawing ---
    # Call the recursive function to begin generating the fractal.
    print(f"Generating fractal with length={initial_length}, level={recursion_level}, angle={branch_angle}...")
    draw_fractal(artist, initial_length, recursion_level, branch_angle)
    print("Fractal generation complete!")

    # Keep the window open until it's manually closed.
    screen.mainloop()

# --- Entry Point of the Script ---
if __name__ == "__main__":
    # This ensures that main() is only called when the script is executed directly,
    # not when imported as a module.
    main()

# --- Example Usage ---
# To run this code:
# 1. Save it as a Python file (e.g., fractal_generator.py).
# 2. Open a terminal or command prompt.
# 3. Navigate to the directory where you saved the file.
# 4. Run the command: python fractal_generator.py
#
# You can experiment by changing the initial_length, recursion_level, and branch_angle
# in the main() function to create different fractal patterns. For example:
# - Increase recursion_level for more intricate details (be aware of performance).
# - Decrease branch_angle for a more spread-out fractal.
# - Increase branch_angle for a more condensed fractal.
# - Change PEN_COLOR and BACKGROUND_COLOR for different aesthetics.